### PR TITLE
Fix timestamp order passed to Job Config History

### PR DESCRIPTION
**Pull request by deshantm**

### CODE REVIEW

**Comment by deshantm** [comment]
fixed the test to match the code change.

**Comment by deshantm** [comment]
why is this happening: https://jenkins.ci.cloudbees.com/job/plugins/job/mail-watcher-plugin/42/org.jenkins-ci.plugins$mail-watcher-plugin/testReport/org.jenkinsci.plugins.mailwatcher/NodeStatusTest/correctlyIdentifySlave/ ?

**Comment by olivergondza** [comment]
The change looks good to me, let me look at the test failures.

**Comment by olivergondza** [comment]
It work for me locally and the master branch fails on the CI server as well.

**Pull request merged**
